brew 'stow'

brew 'bash'
brew 'bash-completion'

brew 'jq'
brew 'tree'
brew 'wget', args: ['with-iri']
brew 'ctags'
brew 'cmake'
brew 'gnu-tar'
brew 'gnu-sed'
brew 'coreutils'
brew 'findutils'
brew 'grep', args: ['with-default-names']

tap 'neovim/neovim'
brew 'neovim'
brew 'vimpager'

brew 'hg'
brew 'git'
brew 'gist'

brew 'go'
brew 'node'
brew 'ruby'
brew 'markdown'
brew 'shellcheck'

cask_args appdir: '/Applications'
tap 'caskroom/cask'

cask 'iterm2'

brew 'awscli'
cask 'aws-vault'
cask 'google-cloud-sdk'

brew 'tfenv'

brew 'kubernetes-cli'
brew 'kubernetes-helm'

cask 'docker'
cask 'vagrant'
#cask 'virtualbox'

# cask 'cura'
cask 'slack'
cask 'spotify'
cask 'caffeine'
cask 'dropbox'
cask 'keybase'
cask '1password'
cask '1password-cli'
cask 'google-chrome'

tap 'caskroom/drivers'
cask 'sonos'

cask 'caskroom/fonts/font-hack'
