cask_args appdir: '/Applications'
tap 'caskroom/cask'

brew 'stow'

brew 'bash'
brew 'bash-completion'

brew 'jq'
brew 'tree'
brew 'wget', args: ['with-iri']
brew 'ctags'
brew 'gnu-tar'
brew 'gnu-sed'
brew 'coreutils'
brew 'findutils'
brew 'grep', args: ['with-default-names']

cask 'iterm2'

tap 'neovim/neovim'
brew 'neovim'

brew 'vim', args: ['override-system-vi', 'with-lua']
brew 'vimpager'

brew 'hg'
brew 'git'
brew 'gist'

brew 'go'
brew 'node'
brew 'ruby'
brew 'markdown'
brew 'shellcheck'

brew 'awscli'
cask 'aws-vault'

brew 'kubernetes-cli'
brew 'kubernetes-helm'

cask 'docker'
cask 'vagrant'
cask 'virtualbox'

# cask 'cura'
cask 'spotify'
cask 'caffeine'
cask 'dropbox'
cask 'keybase'
cask 'google-chrome'

tap 'caskroom/drivers'
cask 'sonos'

mas '1Password', id: 443987910

cask 'caskroom/fonts/font-hack'
