#!/usr/bin/env bash

protected_branches='master prod'

remote_name="$1"
remote_url="$2"

while read local_ref local_sha remote_ref remote_sha; do
    for branch in $protected_branches; do
        if grep -q "${branch}" <<< ${remote_ref}; then
            read -p "pushing to $remote_ref - are you sure? [y|n] " -n 1 -r < /dev/tty
            echo

            if echo "$REPLY" | grep -E '^[Yy]$' > /dev/null; then
                exit 0
            fi
            exit 1
        fi
    done
done

exit 0
