#! /bin/sh
# Install command-line tools using Homebrew
# Usage: `brew bundle Brewfile`

# Make sure we’re using the latest Homebrew
brew update

# Upgrade any already-installed formulae
brew upgrade

# Install GNU core utilities (those that come with OS X are outdated)
# Don’t forget to add `$(brew --prefix coreutils)/libexec/gnubin` to `$PATH`.
brew install coreutils
# Install some other useful utilities like `sponge`
brew install moreutils
# Install GNU `find`, `locate`, `updatedb`, and `xargs`, `g`-prefixed
brew install findutils
# Install GNU `sed`, overwriting the built-in `sed`
brew install gnu-sed --default-names
# Install Bash 4
# Note: don’t forget to add `/usr/local/bin/bash` to `/etc/shells` before running `chsh`.
brew install bash
brew install bash-completion

# Install wget with IRI support
brew install wget --enable-iri

# Install more recent versions of some OS X tools
brew install vim --override-system-vi
brew install homebrew/dupes/grep

# Install other useful binaries
brew install ack
brew install git
brew install tree

brew install hub

# datastore - removed in favor of docker
brew install postgresql
#install zookeeper

# languages
brew install scala
brew install python

# build tools
brew install maven
brew install gradle
brew install sbt
brew install ant

# tools
brew install homebrew/binary/jad

brew install tuntap
brew install openconnect
brew install git-flow

brew install docker
brew install boot2docker

brew install stow

# Remove outdated versions from the cellar
brew cleanup
brew list

