#! /bin/sh

# get ready
brew update --all
brew upgrade --all

# basics
brew install stow

brew install coreutils
brew install findutils --with-default-names
brew install gnu-sed --with-default-names
brew install bash
brew install bash-completion

brew install wget --with-iri
brew install vim --override-system-vi --with-lua
brew install vimpager
brew install ctags
brew install homebrew/dupes/grep --with-default-names

brew install tree

# vcs
brew install git
brew install hg

brew install hub
brew install gist

# db
brew install postgresql

# lang
brew install go

brew install scala
brew install scalastyle

brew install checkstyle

# build tools
brew install maven
brew install gradle
brew install sbt
brew install ant

# for vim java integration
brew install nailgun

# virt
brew install docker
brew install boot2docker

# other
brew install keybase

# Remove outdated versions from the cellar
brew cleanup
brew list
