#! /bin/sh

brew update
brew upgrade

brew install coreutils
brew install findutils
brew install gnu-sed --with-default-names
brew install bash
brew install bash-completion

brew install wget --enable-iri
brew install vim --override-system-vi --with-lua
brew install vimpager
brew install ctags
brew install homebrew/dupes/grep

# Install other useful binaries
brew install ack
brew install git
brew install hg
brew install tree

brew install hub

brew install postgresql
brew install go

# build tools
brew install maven
brew install gradle
brew install sbt
brew install ant

# tools
brew install homebrew/binary/jad

brew install docker
brew install boot2docker

brew install stow

# Remove outdated versions from the cellar
brew cleanup
brew list

