#! /bin/sh

brew update
brew upgrade

# Install GNU core utilities (those that come with OS X are outdated)
# Don’t forget to add `$(brew --prefix coreutils)/libexec/gnubin` to `$PATH`.
brew install coreutils
brew install moreutils
brew install findutils
brew install gnu-sed --default-names
brew install bash
brew install bash-completion

brew install wget --enable-iri
brew install vim --override-system-vi --with-lua
brew install homebrew/dupes/grep

# Install other useful binaries
brew install ack
brew install git
brew install tree

brew install hub

brew install postgresql
brew install go

# build tools
brew install maven
brew install gradle
brew install sbt
brew install ant

# tools
brew install homebrew/binary/jad

brew install docker
brew install boot2docker

brew install stow

# Remove outdated versions from the cellar
brew cleanup
brew list

