#! /bin/sh

brew install caskroom/cask/brew-cask
brew tap caskroom/versions

brew cask install dropbox
brew cask install google-chrome
brew cask install iterm2
brew cask install sublime-text3
brew cask install virtualbox
brew cask install vagrant

brew cask install visualvm
brew cask install intellij-idea
brew cask install pgadmin3

# quicklook plugins
brew cask install quicklook-json
brew cask install quicklook-csv
brew cask install qlcolorcode
brew cask install qlmarkdown
brew cask install qlprettypatch
brew cask install betterzipql

brew cask install alfred
brew cask install adium
brew cask install spotify

brew cask install caskroom/versions/java7
brew cask install java

brew cask install hipchat
brew cask install slack
brew cask install caffeine
brew cask install evernote
brew cask install mou

# paid for on app store
#brew cask install flexiglass
#brew cask isntall onepassword

brew cask install switchresx

brew cask cleanup
brew cask list

